[tool.pylint.main]
disable = ["missing-module-docstring",
           "missing-function-docstring",
           "missing-class-docstring"]

# Pylint can not import Keras somehow
ignored-modules = "tensorflow.keras"

[tool.pylint]
good-names = ["Piece_Classifier_Model",
              "Color_Classifier_Model",
              "Fullmove_Counter_Model",
              "Halfmove_Counter_Model",
              "X"]
good-names-rgxs = "^[_a-z][_a-z0-9]?$"

[tool.pylint.format]
indent-string = "  "
